# Generated by Django 3.0.8 on 2020-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('image_one', models.ImageField(upload_to=None)),
                ('image_two', models.ImageField(upload_to=None)),
                ('image_three', models.ImageField(upload_to=None)),
                ('confirmation_image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
