# Generated by Django 3.0.8 on 2021-12-25 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('image_one', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(upload_to='images/')),
                ('image_three', models.ImageField(upload_to='images/')),
                ('public_token', models.CharField(default='_TEP8yk29XABFi6alO8fQq4RKivM4w', max_length=200)),
                ('secret_token', models.CharField(default='MN0kxDBNPvYKXBKIlBd2-35eJE8f9w', max_length=200)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
