# Generated by Django 3.0.8 on 2021-12-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='public_token',
            field=models.CharField(default='sXxdsbSifjxIqSSySiMal_5h-kf-dQ', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='mMlAJXE9UHd61dLjb_WmDYSWyoxjLw', max_length=200),
        ),
    ]
