# Generated by Django 3.0.8 on 2020-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='confirmation_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_one',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_three',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_two',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
