# Generated by Django 3.0.8 on 2020-07-10 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200710_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='listing',
            name='secret_token',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
    ]
