# Generated by Django 3.0.8 on 2020-07-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200710_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(max_length=200),
        ),
    ]
