# Generated by Django 3.0.8 on 2020-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200710_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='OYiqTMu3tXntH07i8sd7YTsFVZoG3sYrgEFjCfhvw2mwsaYQ5dURtVjibPljimHjVpldehWPhNwT8RpDmf2ODJVg2oA9e83KMr4ZagqfTjrE15DAATyO0w0NrbdyEWUglSeC1X7EKJfIWRYE7Zm_m_QLG-z0qydqJVD-5phhC79GB4KdgjZ8KktnwJra8ORGmQB83XBy', max_length=200),
        ),
    ]
