# Generated by Django 3.0.8 on 2020-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200710_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='diNkqCbu9lX5VL-nRci-HsyDW-sY', max_length=22),
        ),
    ]
