# Generated by Django 3.0.8 on 2020-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200710_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='cy9GW04yjZyZ1MNSS3Pb4GEZMCh5cg', max_length=200),
        ),
    ]
