# Generated by Django 3.0.8 on 2020-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200710_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='brSLtw3iNY8JTkhId_kwxm4bT20xug', max_length=200),
        ),
    ]
