# Generated by Django 3.0.8 on 2020-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200716_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='confirmation_image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='nx7avb_1qfcheNIAMq2oAAc5iVEpdA', max_length=200),
        ),
    ]
