# Generated by Django 3.0.8 on 2020-07-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200716_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='public_token',
            field=models.CharField(default='F8EeW8QVA7NhwUqK6D8st1MoIYIJ9g', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='secret_token',
            field=models.CharField(default='_v1WpoCFd-okj9Hv-TVCHGBNmAzZDA', max_length=200),
        ),
    ]
